site_name: Dionysos server
site_url: https://github.com/Brawdunoir/dionysos-server
nav:
  - Getting started: index.md
  - Requests:
      - requests/changeusername.md
      - requests/newroom.md
      - requests/joinroom.md
      - Answer Join Room Request: requests/joinroomanswer.md
      - Quit Room: requests/quitroom.md
      - Kick Peer: requests/kickpeer.md
      - Send Message: requests/message.md
  - Responses:
      - responses/newpeers.md
theme: material
